repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
        -   id: check-yaml
        -   id: check-json
        -   id: check-xml
        -   id: mixed-line-ending
        -   id: end-of-file-fixer
        -   id: trailing-whitespace

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: 7a279fad9f0f4b98c7f75fc966931bbd7034b0de
    hooks:
      - id: pretty-format-java
        args: [--autofix]
